name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: flake8 app.py
      - name: Run security checks with bandit
        run: bandit -r app.py
      - name: Run tests
        run: pytest
      - name: Test app startup
        run: |
          python -m flask --app app run &
          sleep 5
          curl -f http://127.0.0.1:5000/
        env:
          FLASK_ENV: development
